\chapter{Genome assembly of Candida nivariensis}
\label{chap:rnw}

<<label=opts, results='hide', echo=FALSE, message = FALSE, warning=FALSE>>=
library(knitr)
opts_chunk$set(echo=FALSE, prompt=FALSE, message=FALSE, warning=FALSE, comment="", results='hide')
@

<<label=some_code, echo=FALSE >>=
## Run some R code
date <- date()
@

This document was generated on \Sexpr{date}.

As shown in Figure \ref{fig:mummer} and in Table \ref{tab:rtab1} we can see that bla bla \citep{B}.


<<results = 'asis', eval = TRUE>>=
what <- "figure"
figname <- "mummer"
title <- "Mummer between stuff"
desc <- "{\\bf (a)} blah first point {\\bf (b)} blah second point {\\bf (c)} blaih thrid panel "
shortname <- "fig:mummer"
where <- "[!ht]"

figstr <- paste0('\\begin{', what ,'}', where ,'
\\centering
\\includegraphics[width = 1\\linewidth,keepaspectratio]{figure/', figname, '.pdf}
\\caption[', title ,']{{\\bf ', title  ,'.} ', desc ,' }
\\label{', shortname ,'}
\\end{', what ,'}
')
cat(figstr)
@



<<label=some_tab, results = "asis">>=
## Example R table
library('xtable')
df <- data.frame(A = 1:10, B = round(rnorm(10), 3))
xtab <- xtable(df, digits = 2, caption = '\\bf{ Table title } Table description', label = 'tab:rtab1')
print.xtable(xtab, include.rownames = FALSE)
@
